add matrixCopy(test file)

diff --git a/program1/matrixCopy b/program1/matrixCopy
--- a/program1/matrixCopy
+++ b/program1/matrixCopy
@@ -1,5 +1,30 @@
 #!/bin/bash
 
+function dtmError(){
+if [ "$#" = "1" ] # If input type is stdin, 
+then
+    cat > "$1" # let user type a matrix and store data to a temp file.
+elif [ "$#" = "2" ] # If input type is file, 
+then
+    # Check if input file is readable
+    if [ -f "$2" ] # Read a file 
+    then
+        echo "$2 exists" >/dev/null # Yes, file readable. Do nothing.
+    else
+        echo "$2 does NOT EXIST!!" >&2 # File is not readable. Error to stderr and return 1.
+        return 1
+    fi
+    # Read a valid file
+    while read myLine # read a file and store data to temp file.
+    do
+        echo "$myLine" >> "$1"
+    done < "$2" # Read the first argument which is a file.
+else # If number of arguments is more than 1 (invalid), error to stderr and return 1.
+    echo "You have more than 1 argument. This is INVALID!!" >&2
+    return 1
+fi
+}
+
 function dims(){
   # NAME
   #   dims - Outputs dimensions of a matrix
@@ -13,29 +38,9 @@ function dims(){
 
 # Choose the type of argument between file and stdin.
 datafilepath="datafile$$" # Temp file to store data.
-if [ "$#" = "0" ] # If input type is stdin, 
-then
-    cat > "$datafilepath" # let user type a matrix and store data to a temp file.
-elif [ "$#" = "1" ] # If input type is file, 
-then
-    # Check if input file is readable
-    if [ -f "$1" ] # Read a file 
-    then
-        echo "$1 exists" >/dev/null # Yes, file readable. Do nothing.
-    else
-        echo "$1 does NOT EXIST!!" >&2 # File is not readable. Error to stderr and return 1.
-        return 1
-    fi
-    # Read a valid file
-    while read myLine # read a file and store data to temp file.
-    do
-        echo "$myLine" >> $datafilepath
-    done < $1 # Read the first argument which is a file.
-else # If number of arguments is more than 1 (invalid), error to stderr and return 1.
-    echo "You have more than 1 argument. This is INVALID!!" >&2
-    return 1
-fi
 
+dtmError "$datafilepath" "${@:1}"
+echo "status value: $?"
 # Process:
 # Traverse all rows and columns of matrix.
 # Increment rowNum and colNum for every row and column, respectively.
@@ -51,12 +56,12 @@ rowNum=`expr $rowNum + 1` # Increment number of row.
     do
         colNum=`expr $colNum + 1` # Increment number of column.
     done
-done < $datafilepath # Read a temp file.
+done < "$datafilepath" # Read a temp file.
 
 colNum=`expr $colNum / $rowNum` # Divide number of column by number of row.
 echo "$rowNum $colNum" # Print out result.
 
-rm -f $datafilepath # Delete a temp file
+rm -f "$datafilepath" # Delete a temp file
 
 return 0 # Return 0, which means the input is valid.
 }
